backend:
  name: git-gateway
  branch: main

site_url: "https://sawritings.netlify.app"

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "writings"
    label: "Writings"
    files:
      - file: "data/writings.json"
        label: "All Writings"
        name: "writings"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "text" }
